# Generated by Django 5.0 on 2023-12-15 09:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='image_1/', verbose_name='Фото 1')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Обращение директоров',
                'verbose_name_plural': 'Обращение директоров',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='image/', verbose_name='фото')),
                ('urls', models.URLField(verbose_name='Ссылка на фото')),
            ],
            options={
                'verbose_name': 'Наши проекты',
                'verbose_name_plural': 'Наш проект',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('contact', models.CharField(max_length=25, verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('instagram', models.URLField(verbose_name='Ссылка на инстаграм')),
                ('whatsapp', models.URLField(verbose_name='Ссылка на ватсап')),
                ('facebook', models.URLField(verbose_name='Ссылка на фейсбук')),
                ('youtube', models.URLField(verbose_name='Ссылка на ютуб')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройка сайта',
            },
        ),
    ]
